//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FamiTracker.rc
//
#define ID_INDICATOR_OCTAVE             1
#define IDC_WRITE_BIN                   3
#define IDC_IMPORT                      4
#define IDC_NEW_DATA                    4
#define IDC_WRITE_PRG                   5
#define IDC_SAVE                        6
#define IDD_ABOUTBOX                    100
#define IDR_HTML_ABOUTBOX               106
#define ID_NEXT_FRAME                   109
#define ID_PREV_FRAME                   110
#define ID_TRACKER_TOGGLE_PLAY          111
#define IDC_EDIT_INST                   112
#define ID_CMD_OCTAVE_NEXT              115
#define ID_CMD_OCTAVE_PREVIOUS          116
#define ID_CMD_PASTEMIXED               117
#define ID_CMD_PASTEOVERWRITE           118
#define ID_CMD_NEXT_INSTRUMENT          119
#define ID_CMD_PREV_INSTRUMENT          120
#define IDR_MAINFRAME                   128
#define ID_INDICATOR_RATE               129
#define IDR_FamiTrackerTYPE             129
#define ID_INDICATOR_TIME               130
#define IDD_MAINFRAME                   131
#define IDS_CLIPBOARD_ERROR             131
#define IDS_FILE_OPEN_ERROR             132
#define IDS_FILE_VALID_ERROR            133
#define IDS_FILE_VERSION_ERROR          134
#define IDS_INST_LIMIT                  135
#define IDS_CLIPBOARD_OPEN_ERROR        136
#define IDS_CLIPBOARD_NOT_AVALIABLE     137
#define IDS_SAVE_ERROR                  138
#define IDS_INSTRUMENT_FILE_FAIL        139
#define IDS_SAMPLES_NEEDED              140
#define IDS_OPEN                        141
#define IDS_SAVE_ERROR_REASON           142
#define IDS_START_ERROR                 143
#define IDS_SOUNDGEN_ERROR              144
#define IDD_PERFORMANCE                 145
#define IDS_SOUNDGEN_CLOSE_ERR          145
#define IDD_SPEED                       146
#define IDS_STRING146                   146
#define IDS_OUT_OF_SLOTS                146
#define IDD_PCMIMPORT                   147
#define IDI_INST_2A03                   153
#define IDD_INSTRUMENT_INTERNAL         158
#define IDD_INSTRUMENT_DPCM             159
#define IDD_INSTRUMENT                  160
#define IDB_SAMPLEBG                    169
#define IDB_KEY_BLACK                   172
#define IDB_KEY_BLACK_MARK              173
#define IDB_KEY_WHITE                   174
#define IDB_KEY_WHITE_MARK              176
#define IDI_INST_2A03INV                179
#define IDD_CONFIG_APPEARANCE           180
#define IDD_MIDIIMPORT                  181
#define IDD_CONFIG_GENERAL              183
#define IDD_PROPERTIES                  185
#define IDD_CONFIG_MIDI                 194
#define IDR_POPUP                       198
#define IDD_CONFIG_SOUND                201
#define IDS_FILE_LOAD_ERROR             204
#define IDS_CONFIG_WINDOW               205
#define IDR_INSTRUMENT                  205
#define IDS_WELCOME                     206
#define IDB_INSTRUMENT_TOOLS            208
#define IDD_CONFIG_SHORTCUTS            211
#define IDD_OCTAVE                      212
#define IDI_INST_VRC6                   214
#define IDD_INSTRUMENT_VRC6             216
#define IDI_INST_VRC6INV                217
#define IDD_EXPORT                      218
#define IDD_ABOUT                       220
#define IDC_INSTRUMENTS                 1001
#define IDC_INSTSETTINGS                1002
#define IDC_MODIFIERS                   1003
#define IDC_ADD_INST                    1004
#define IDC_INSTNAME                    1005
#define IDC_SEQ_INDEX                   1007
#define IDC_MOD_SELECT_SPIN             1008
#define IDC_PARSE_MML                   1010
#define IDC_ROWS                        1019
#define IDC_ROWS_SPIN                   1020
#define IDC_SPEED_SPIN                  1022
#define IDC_TEMPO_SPIN2                 1023
#define IDC_TEMPO_SPIN                  1023
#define IDC_FRAMES                      1026
#define IDC_FRAME_SPIN                  1027
#define IDC_KEYSTEP                     1028
#define IDC_KEYSTEP_SPIN                1029
#define IDC_TEMPO                       1030
#define IDC_FRAME_DEC                   1035
#define IDC_FRAME_INC                   1036
#define IDC_KEYREPEAT                   1038
#define IDC_SAMPLE_RATE                 1039
#define IDC_SAMPLE_SIZE                 1040
#define IDC_BUF_LENGTH                  1041
#define IDC_BASS_FREQ                   1042
#define IDC_CHANGE_ALL                  1043
#define IDC_TREBLE_DAMP                 1043
#define IDC_BUF_LEN                     1044
#define IDC_BASS_FREQ_T                 1045
#define IDC_LOG                         1045
#define IDC_NAME                        1046
#define IDC_TREBLE_DAMP_T               1046
#define IDC_ARTIST                      1047
#define IDC_TREBLE_FREQ                 1047
#define IDC_COPYRIGHT                   1048
#define IDC_TREBLE_FREQ_T               1048
#define IDC_VOL                         1050
#define IDC_VOLUME_T                    1050
#define IDC_SPEED_SLD                   1051
#define IDC_SPEED                       1052
#define IDC_QUALITY                     1053
#define IDC_VOLUME                      1054
#define IDC_IMPORT_BAR                  1055
#define IDC_QUALITY_FRM                 1056
#define IDC_VOLUME_FRM                  1057
#define IDC_CPU                         1058
#define IDC_VOLUME_FRM2                 1058
#define IDC_CPU_BAR                     1059
#define IDC_FRAMERATE                   1060
#define IDC_UNDERRUN                    1061
#define IDC_OPT_WRAPCURSOR              1062
#define IDC_OPT_FREECURSOR              1063
#define IDC_DEVICES                     1063
#define IDC_OPT_WAVEPREVIEW             1064
#define IDC_MASTER_SYNC                 1065
#define IDC_OPT_KEYREPEAT               1065
#define IDC_KEY_RELEASE                 1066
#define IDC_OPT_HEXROW                  1066
#define IDC_CHANMAP                     1067
#define IDC_SONG_NAME                   1067
#define IDC_SONG_ARTIST                 1068
#define IDC_MML                         1068
#define IDC_VELOCITY                    1068
#define IDC_OPT_FRAMEPREVIEW            1068
#define IDC_SONG_COPYRIGHT              1069
#define IDC_OPT_NODPCMRESET             1069
#define IDC_ARPEGGIATE                  1069
#define IDC_OPT_NODPCMRESET2            1070
#define IDC_OPT_NOSTEPMOVE              1070
#define IDC_FONT                        1071
#define IDC_OPT_PATTENRCOLORS           1071
#define IDC_ABOUT                       1072
#define IDC_RESTORE                     1073
#define IDC_CLIP                        1074
#define IDC_SHORTCUTS                   1074
#define IDC_OCTAVE                      1075
#define IDC_SAMPLES                     1076
#define IDC_INST_TAB                    1077
#define IDC_TABLE                       1078
#define IDC_PITCH                       1079
#define IDC_LOAD                        1080
#define IDC_UNLOAD                      1081
#define IDC_SAMPLE_LIST                 1082
#define IDC_SPACE                       1083
#define IDC_KEYBOARD                    1084
#define IDC_FREE_SEQ                    1086
#define IDC_CHANNEL1                    1088
#define IDC_CHANNEL2                    1089
#define IDC_CHANNEL3                    1090
#define IDC_CHANNEL4                    1091
#define IDC_CHANNEL5                    1092
#define IDC_PATLEN                      1093
#define IDC_STYLE1                      1094
#define IDC_STYLE2                      1098
#define IDC_STYLE3                      1099
#define IDC_COL_ITEM                    1100
#define IDC_PICK_COL                    1101
#define IDC_COL_PREVIEW                 1102
#define IDC_SCHEME                      1104
#define IDC_PREVIEW                     1105
#define IDC_ORG                         1106
#define IDC_BANKSWITCH                  1111
#define IDC_PAL                         1112
#define IDC_BANKOPTIMIZE                1113
#define IDC_LOOP                        1118
#define IDC_WRITE_NSF                   1119
#define IDC_OUTDEVICES                  1124
#define IDC_INDEVICES                   1126
#define IDC_SUBTUNE                     1127
#define IDC_SUBTUNES                    1128
#define IDC_PAGELENGTH                  1129
#define IDC_KEYS                        1131
#define IDC_DEFAULT                     1132
#define IDC_EXPANSION                   1135
#define IDC_CLOSE                       1137
#define IDC_SAVENSF                     1142
#define IDC_OUTPUT                      1143
#define IDC_SAVEBIN                     1144
#define IDC_SAVEPRG                     1145
#define IDC_BUTTON1                     1146
#define IDC_DEBUG                       1146
#define IDC_ADD                         1146
#define IDC_REMOVE                      1147
#define ID_TRACKER_PLAY                 32771
#define ID_TRACKER_PLAYPATTERN          32775
#define ID_TRACKER_STOP                 32776
#define ID_TRACKER_EDIT                 32777
#define ID_TRACKER_KILLSOUND            32778
#define ID_FILE_CREATE_NSF              32807
#define ID_FILE_SOUNDSETTINGS           32809
#define ID_EDIT_DELETE                  32820
#define ID_EDIT_UNLOCKCURSOR            32823
#define ID_TRACKER_NTSC                 32824
#define ID_TRACKER_PAL                  32825
#define ID_SPEED_DEFALUT                32827
#define ID_SPEED_CUSTOM                 32828
#define ID_HELP_PERFORMANCE             32829
#define ID_EDIT_PASTEOVERWRITE          32831
#define ID_TRANSPOSE_INCREASENOTE       32833
#define ID_TRANSPOSE_DECREASENOTE       32834
#define ID_TRANSPOSE_INCREASEOCTAVE     32835
#define ID_TRANSPOSE_DECREASEOCTAVE     32836
#define ID_EDIT_SELECTALL               32847
#define ID_FILE_GENERALSETTINGS         32851
#define ID_EDIT_ENABLEMIDI              32853
#define ID_FRAME_INSERT                 32854
#define ID_FRAME_REMOVE                 32855
#define ID_TRACKER_PLAYROW              32858
#define ID_FILE_IMPORTMIDI              32863
#define ID_CREATE_NSF                   32867
#define ID_BUTTON32892                  32892
#define ID_SPEED_DEFAULT                32893
#define ID_MODULE_MODULEPROPERTIES      32895
#define ID_EDIT_PASTEMIX                32899
#define ID_MODULE_MOVEFRAMEDOWN         32902
#define ID_MODULE_MOVEFRAMEUP           32903
#define ID_BUTTON32905                  32905
#define ID_BUTTON32906                  32906
#define ID_BUTTON32907                  32907
#define ID_BUTTON32908                  32908
#define ID_MODULE_SAVEINSTRUMENT        32909
#define ID_MODULE_LOADINSTRUMENT        32911
#define ID_EDIT_CLEAREVERYTHING         32912
#define ID_MODULE_ADDINSTRUMENT         32915
#define ID_MODULE_REMOVEINSTRUMENT      32916
#define ID_POPUP_EFFECTS                32920
#define ID_EFFECTS_0XX                  32921
#define ID_EFFECTS_1XX                  32922
#define ID_EFFECTS_2XX                  32923
#define ID_EFFECTS_4XX                  32924
#define ID_EFFECTS_7XX                  32925
#define ID_EFFECTS_CXX                  32927
#define ID_EFFECTS_DXX                  32928
#define ID_EFFECTS_EXX                  32929
#define ID_EFFECTS_FXX                  32930
#define ID_EFFECTS_GXX                  32931
#define ID_EFFECTS_HXX                  32932
#define ID_EFFECTS_IXX                  32933
#define ID_EFFECTS_PXX                  32934
#define ID_EFFECTS_ZXX                  32935
#define ID_EFFECTS_BXX                  32936
#define ID_TRACKER_SOLOCHANNEL          32940
#define ID_TRACKER_TOGGLECHANNEL        32941
#define ID_EDIT_GRADIENT                32942
#define ID_MODULE_EDITINSTRUMENT        32943
#define ID_BUTTON32944                  32944
#define ID_NEXT_SONG                    32944
#define ID_BUTTON32945                  32945
#define ID_PREV_SONG                    32945
#define ID_EDIT_INSTRUMENTMASK          32948
#define ID_TRACKER_SWITCHTOTRACKINSTRUMENT 32949
#define ID_POPUP_EFFECTS32950           32950
#define ID_FILE_ADDSONG                 32951
#define ID_INDICATOR_INSTRUMENT         61204
#define ID_INDICATOR_TEMPO              61205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32952
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
