//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FamiTracker.rc
//
#define ID_INDICATOR_OCTAVE             1
#define ID_ADD                          2
#define ID_REMOVE                       3
#define IDC_APPLY                       3
#define IDC_IMPORT                      4
#define IDC_DPCM_ADD                    5
#define IDC_SAVE                        6
#define IDD_ABOUTBOX                    100
#define IDR_HTML_PERFORMANCEDLG         103
#define IDR_MAINFRAME                   128
#define IDR_FamiTrackerTYPE             129
#define ID_INDICATOR_RATE               129
#define ID_INDICATOR_TIME               130
#define IDD_MAINFRAME                   131
#define IDD_SND_SETTINGS                136
#define IDD_NSF                         137
#define IDD_PERFORMANCE                 145
#define IDD_SPEED                       146
#define IDD_PCMIMPORT                   147
#define IDD_OPTIONS                     148
#define IDD_MIDICONFIG                  149
#define IDI_INST_2A03                   153
#define IDI_ICON1                       156
#define IDD_DPCM                        157
#define IDD_INSTRUMENT_INTERNAL         158
#define IDD_INSTRUMENT_DPCM             159
#define IDD_INSTRUMENT                  160
#define IDB_BITMAP1                     169
#define IDB_SAMPLEBG                    169
#define IDB_KEY_BLACK                   172
#define IDB_KEY_BLACK_MARK              173
#define IDB_KEY_WHITE                   174
#define IDB_KEY_WHITE_MARK              176
#define IDI_ICON2                       179
#define IDI_INST_2A03INV                179
#define IDC_INSTRUMENTS                 1001
#define IDC_INSTSETTINGS                1002
#define IDC_MODIFIER                    1003
#define IDC_SEQUENCE_LIST               1003
#define IDC_ADD_INST                    1004
#define IDC_INSTNAME                    1005
#define IDC_REMOVE_INST                 1006
#define IDC_MOD_SELECT                  1007
#define IDC_EDIT_INST                   1007
#define IDC_SEQ_INDEX                   1007
#define IDC_MOD_SELECT_SPIN             1008
#define IDC_ADD_MOD                     1009
#define IDC_INSERT                      1009
#define IDC_DPCM                        1010
#define IDC_PARSE_MML                   1010
#define IDC_REMOVE_MOD                  1011
#define IDC_REMOVE                      1011
#define IDC_DPCM_LOAD                   1012
#define IDC_MOD_LENGTH                  1015
#define IDC_LENGTH                      1015
#define IDC_MOD_LENGTH_SPIN             1016
#define IDC_MOD_VALUE                   1017
#define IDC_VALUE                       1017
#define IDC_MOD_VALUE_SPIN              1018
#define IDC_ROWS                        1019
#define IDC_DPCM_REMOVE                 1019
#define IDC_ROWS_SPIN                   1020
#define IDC_DPCM_IMPORT                 1020
#define IDC_TEMPO                       1021
#define IDC_DPCM_SAVE                   1021
#define IDC_TEMPO_SPIN                  1022
#define IDC_MOD_INDEX                   1024
#define IDC_MOD_INDEX_SPIN              1025
#define IDC_PATTERNS                    1026
#define IDC_FRAMES                      1026
#define IDC_PATTERNS_SPIN               1027
#define IDC_KEYSTEP                     1028
#define IDC_LIST                        1029
#define IDC_KEYSTEP_SPIN                1029
#define IDC_CLOSE                       1030
#define IDC_CLOSE2                      1031
#define IDC_CLOSE3                      1032
#define IDC_CLOSE4                      1033
#define IDC_CLOSE5                      1034
#define IDC_FRAME_DEC                   1035
#define IDC_FRAME_INC                   1036
#define IDC_KEYREPEAT                   1038
#define IDC_SAMPLE_RATE                 1039
#define IDC_SAMPLE_SIZE                 1040
#define IDC_BUF_LENGTH                  1041
#define IDC_BASS_FREQ                   1042
#define IDC_CHANGE_ALL                  1043
#define IDC_TREBLE_DAMP                 1043
#define IDC_BUF_LEN                     1044
#define IDC_INFO                        1045
#define IDC_BASS_FREQ_T                 1045
#define IDC_NAME                        1046
#define IDC_TREBLE_DAMP_T               1046
#define IDC_ARTIST                      1047
#define IDC_TREBLE_FREQ                 1047
#define IDC_COPYRIGHT                   1048
#define IDC_TREBLE_FREQ_T               1048
#define IDC_KEEP_SYMBOLS                1049
#define IDC_SAMPLES_SIZE                1050
#define IDC_SPEED_SLD                   1051
#define IDC_SPEED                       1052
#define IDC_QUALITY                     1053
#define IDC_VOLUME                      1054
#define IDC_IMPORT_BAR                  1055
#define IDC_QUALITY_FRM                 1056
#define IDC_VOLUME_FRM                  1057
#define IDC_CPU                         1058
#define IDC_VOLUME_FRM2                 1058
#define IDC_CPU_BAR                     1059
#define IDC_FRAMERATE                   1060
#define IDC_UNDERRUN                    1061
#define IDC_OPT_WRAPCURSOR              1062
#define IDC_OPT_FREECURSOR              1063
#define IDC_DEVICES                     1063
#define IDC_OPT_WAVEPREVIEW             1064
#define IDC_MASTER_SYNC                 1065
#define IDC_OPT_KEYREPEAT               1065
#define IDC_KEY_RELEASE                 1066
#define IDC_CHANMAP                     1067
#define IDC_SONG_NAME                   1067
#define IDC_SONG_ARTIST                 1068
#define IDC_MML                         1068
#define IDC_VELOCITY                    1068
#define IDC_SONG_COPYRIGHT              1069
#define IDC_DPCM_NAME                   1069
#define IDC_GRAPH                       1070
#define IDC_FONT                        1071
#define IDC_ABOUT                       1072
#define IDC_RESTORE                     1073
#define IDC_CLIP                        1074
#define IDC_LIST1                       1074
#define IDC_OCTAVE                      1075
#define IDC_SAMPLES                     1076
#define IDC_INST_TAB                    1077
#define IDC_TABLE                       1078
#define IDC_PITCH                       1079
#define IDC_LOAD                        1080
#define IDC_UNLOAD                      1081
#define IDC_SAMPLE_LIST                 1082
#define IDC_SPACE                       1083
#define IDC_KEYBOARD                    1084
#define IDC_FREE_SEQ                    1086
#define ID_TRACKER_PLAY                 32771
#define ID_TRACKER_PLAYPATTERN          32775
#define ID_TRACKER_STOP                 32776
#define ID_TRACKER_EDIT                 32777
#define ID_TRACKER_KILLSOUND            32778
#define ID_Menu                         32779
#define ID_CHANNELS_SQUARE1             32786
#define ID_CHANNELS_SQUARE2             32787
#define ID_CHANNELS_TRIANGLE            32788
#define ID_CHANNELS_NOISE               32789
#define ID_CHANNELS_DPCM                32790
#define ID_TRACKER_TOGGLE_PLAY          -32734
#define ID_FILE_CREATE_NSF              32807
#define ID_FILE_SOUNDSETTINGS           32809
#define ID_EDIT_INCREASEALLFRAMES       32812
#define ID_EDIT_DECREASEALLFRAMESSHIFT  32813
#define ID_NEXT_FRAME                   32814
#define ID_PREV_FRAME                   32815
#define ID_EDIT_FRAMEINC                32817
#define ID_EDIT_FRAMEDEC                32818
#define ID_EDIT_DELETE                  32820
#define ID_EDIT_UNLOCKCURSOR            32823
#define ID_TRACKER_NTSC                 32824
#define ID_TRACKER_PAL                  32825
#define ID_SPEED_DEFALUT                32827
#define ID_SPEED_CUSTOM                 32828
#define ID_HELP_PERFORMANCE             32829
#define ID_Menu32830                    32830
#define ID_EDIT_PASTEOVERWRITE          32831
#define ID_EDIT_TRANSPOSE               32832
#define ID_TRANSPOSE_INCREASENOTE       32833
#define ID_TRANSPOSE_DECREASENOTE       32834
#define ID_TRANSPOSE_INCREASEOCTAVE     32835
#define ID_TRANSPOSE_DECREASEOCTAVE     32836
#define ID_EDIT_SELECTALL               32847
#define ID_FILE_GENERALSETTINGS         32851
#define ID_FILE_MIDISETTINGS            32852
#define ID_EDIT_ENABLEMIDI              32853
#define ID_FRAME_INSERT                 32854
#define ID_FRAME_REMOVE                 32855
#define ID_EDIT_FRAME                   32856
#define ID_TRACKER_PLAYROW              32858
#define ID_INDICATOR_INSTRUMENT         61204
#define ID_INDICATOR_PATTERN            61205
#define ID_INDICATOR_TEMPO              61205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32861
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
