const unsigned int SPEED_PATCH_LOCATION_NONE = 0x52e;
const unsigned int VIBRATO_TABLE_LOCATION_NONE = 0x14a9 + 0x92;		// // //
const unsigned int SPEED_PATCH_LOCATION_VRC6 = 0x536;
const unsigned int VIBRATO_TABLE_LOCATION_VRC6 = 0x167c + 0x92;		// // //
const unsigned int SPEED_PATCH_LOCATION_VRC7 = 0x55e;
const unsigned int VIBRATO_TABLE_LOCATION_VRC7 = 0x1806 + 0x92;		// // //
const unsigned int SPEED_PATCH_LOCATION_MMC5 = 0x53c;
const unsigned int VIBRATO_TABLE_LOCATION_MMC5 = 0x157f + 0x92;		// // //
const unsigned int SPEED_PATCH_LOCATION_FDS = 0x56d;
const unsigned int VIBRATO_TABLE_LOCATION_FDS = 0x1778 + 0x92;		// // //
const unsigned int SPEED_PATCH_LOCATION_N163 = 0x55d;
const unsigned int VIBRATO_TABLE_LOCATION_N163 = 0x17db + 0x92;		// // //
